
export const metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
  };
  
  const dashboard = ({children}) => {
    return (
      <div>{children}</div>
    )
  }
  
  export default dashboard